//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;
using RosMessageTypes.BuiltinInterfaces;

namespace RosMessageTypes.ROSMobile
{
    [Serializable]
    public class Move_commandMsg : Message
    {
        public const string k_RosMessageName = "punktverfolgung/move_command";
        public override string RosMessageName => k_RosMessageName;

        public bool stop;
        public sbyte direction;
        public DurationMsg duration;
        public sbyte speed;
        public bool setSpeed;
        public double value;

        public Move_commandMsg()
        {
            this.stop = false;
            this.direction = 0;
            this.duration = new DurationMsg();
            this.speed = 0;
            this.setSpeed = false;
            this.value = 0.0;
        }

        public Move_commandMsg(bool stop, sbyte direction, DurationMsg duration, sbyte speed, bool setSpeed, double value)
        {
            this.stop = stop;
            this.direction = direction;
            this.duration = duration;
            this.speed = speed;
            this.setSpeed = setSpeed;
            this.value = value;
        }

        public static Move_commandMsg Deserialize(MessageDeserializer deserializer) => new Move_commandMsg(deserializer);

        private Move_commandMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.stop);
            deserializer.Read(out this.direction);
            this.duration = DurationMsg.Deserialize(deserializer);
            deserializer.Read(out this.speed);
            deserializer.Read(out this.setSpeed);
            deserializer.Read(out this.value);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.stop);
            serializer.Write(this.direction);
            serializer.Write(this.duration);
            serializer.Write(this.speed);
            serializer.Write(this.setSpeed);
            serializer.Write(this.value);
        }

        public override string ToString()
        {
            return "Move_commandMsg: " +
            "\nstop: " + stop.ToString() +
            "\ndirection: " + direction.ToString() +
            "\nduration: " + duration.ToString() +
            "\nspeed: " + speed.ToString() +
            "\nsetSpeed: " + setSpeed.ToString() +
            "\nvalue: " + value.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
