//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSMobile
{
    [Serializable]
    public class WD_active_failuresMsg : Message
    {
        public const string k_RosMessageName = "watchdog_node/WD_active_failures";
        public override string RosMessageName => k_RosMessageName;

        public byte current_error_count;
        public WD_errorMsg[] current_errors;

        public WD_active_failuresMsg()
        {
            this.current_error_count = 0;
            this.current_errors = new WD_errorMsg[0];
        }

        public WD_active_failuresMsg(byte current_error_count, WD_errorMsg[] current_errors)
        {
            this.current_error_count = current_error_count;
            this.current_errors = current_errors;
        }

        public static WD_active_failuresMsg Deserialize(MessageDeserializer deserializer) => new WD_active_failuresMsg(deserializer);

        private WD_active_failuresMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.current_error_count);
            deserializer.Read(out this.current_errors, WD_errorMsg.Deserialize, deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.current_error_count);
            serializer.WriteLength(this.current_errors);
            serializer.Write(this.current_errors);
        }

        public override string ToString()
        {
            return "WD_active_failuresMsg: " +
            "\ncurrent_error_count: " + current_error_count.ToString() +
            "\ncurrent_errors: " + System.String.Join(", ", current_errors.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
