//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ROSMobile
{
    [Serializable]
    public class WD_errorMsg : Message
    {
        public const string k_RosMessageName = "ROS_Mobile/WD_error";
        public override string RosMessageName => k_RosMessageName;

        public byte error_id;
        public byte severity_level;
        public string error_description;

        public WD_errorMsg()
        {
            this.error_id = 0;
            this.severity_level = 0;
            this.error_description = "";
        }

        public WD_errorMsg(byte error_id, byte severity_level, string error_description)
        {
            this.error_id = error_id;
            this.severity_level = severity_level;
            this.error_description = error_description;
        }

        public static WD_errorMsg Deserialize(MessageDeserializer deserializer) => new WD_errorMsg(deserializer);

        private WD_errorMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.error_id);
            deserializer.Read(out this.severity_level);
            deserializer.Read(out this.error_description);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.error_id);
            serializer.Write(this.severity_level);
            serializer.Write(this.error_description);
        }

        public override string ToString()
        {
            return "WD_errorMsg: " +
            "\nerror_id: " + error_id.ToString() +
            "\nseverity_level: " + severity_level.ToString() +
            "\nerror_description: " + error_description.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
